const DICTIONARY = {

    en: {
        CURRENT_PLAYER: "Player",
        TURN_MSG: "It is your turn",
        ENTER_MOVE: "Enter your move (row and col)",
        INVALID_MOVE: "You can not make this move, please select again",
        DRAW_MSG: "The result is a draw!",
        WIN_MSG: "Congratulations! You win!",
        PLAY_AGAIN_QUESTION: "Play again (YES/No)? ",
        CONFIRM: "y",
        START_GAME: "Start game",
        SETTINGS: "Settings",
        EXIT: "Exit",
        SELECT_OPTION: "Please select an option.",
        EXITING: "Exiting",
        INVALID_CHOICE: "You may not choose this, please choose again",
        GAME_MODE: "Game mode",
        PLAYER_X: "X",
        PLAYER_O: "O",
        GAME_TITLE: "Tic Tac Toe",
        GAME_DESCRIPTION: "Welcome to Tik Tak Toe! The goal of this game is to get 3 in a row of the same symbol before your opponent!",
        LANGUAGE_MENU_TITLE: "Language options",
        LANGUAGE_CHANGED: "Language has been changed",
        CHOOSE_LANGUAGE: "Select language.",
        ENGLISH: "English",
        NORWEGIAN: "Norwegian",
        GAME_MODE_MENU_TITLE: "Game mode options",
        GAME_MODE_PVP: "Player vs Player",
        GAME_MODE_PVC: "Player vs CPU",
        GAME_MODE_CHANGED: "Game mode has been changed",
        INVALID_OPTION: "You can no make this move, please select a different option",
    },
    no: {
        CURRENT_PLAYER: "Spiller",
        TURN_MSG: "Det er din tur!",
        ENTER_MOVE: "Velg hvor du vil skrive (rekke og rad)",
        INVALID_MOVE: "Du kan ikke utføre dette trekket, prøv igjen.",
        DRAW_MSG: "Det er uavgjort! Dere er like gode!",
        WIN_MSG: "Gratulerer! Du har vunnet spillet!",
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/Nei)? ",
        CONFIRM: "j",
        START_GAME: "Start spill",
        SETTINGS: "Instillinger",
        EXIT: "Avslutt",
        SELECT_OPTION: "Velg et alternativ",
        EXITING: "Avslutter",
        INVALID_CHOICE: "Du kan ikke gjøre dette, prøv igjen",
        GAME_MODE: "Spill modus",
        PLAYER_X: "X",
        PLAYER_O: "O",
        GAME_TITLE: "Tic Tac Toe",
        GAME_DESCRIPTION: "Velkommen til Tic Tac Toe! Målet med dette spillet er å få 3 av det samme symbolet på rad før mostanderen din!",
        LANGUAGE_MENU_TITLE: "Språk instillinger",
        LANGUAGE_CHANGED: "Språk endret",
        CHOOSE_LANGUAGE: "Velg språk",
        ENGLISH: "Engelsk",
        NORWEGIAN: "Norsk",
        GAME_MODE_MENU_TITLE: "Spill modus meny",
        GAME_MODE_PVP: "Spiller mot Spiller",
        GAME_MODE_PVC: "Spiller mot CPU",
        GAME_MODE_CHANGED: "Spill modus endret",
        INVALID_OPTION: "Du kan ikke gjøre dette, prøv igjen",
    }
}

export default DICTIONARY;